[package]
name = "online"
version = "0.1.3-alpha.0"
authors = ["JesÃºs Rubio <jesusprubio@member.fsf.org>"]
edition = "2018"
documentation = "https://docs.rs/online"
include = ["src/**/*", "Cargo.toml"]

description = "ðŸ“¶ Library to check your Internet connectivity"
repository = "https://github.com/jesusprubio/online.git"
readme = "README.md"
keywords = [
  "connection",
  "up",
  "online",
  "tcp",
  "dns"
]
categories = ["network-programming"]
license = "MIT"

[badges]
travis-ci = { repository = "jesusprubio/online" }

[package.metadata.commands]
deps = "cargo install cargo-edit cargo-audit cargo-release cargo-outdated cargo-sync-readme && rustup component add rustfmt clippy"
format = "cargo fmt"
postformat = "cargo clippy"
readme = "cargo sync-readme"
pretest = "cargo cmd format && cargo outdated && cargo audit"
test = "cargo test"
prepublish = "cargo cmd test"
publish = "cargo release minor"

[dependencies]
simple-error = "0.1.13"

[dev-dependencies]
pretty_assertions="0.6.1"
